# Generated by Django 4.1 on 2022-08-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ник'),
        ),
    ]
