# Generated by Django 4.1 on 2022-08-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='rentalperiod',
            options={'verbose_name': 'Период аренды', 'verbose_name_plural': 'Периоды аренды'},
        ),
        migrations.AddField(
            model_name='car',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
